name: Bug report
description: Create a report to help us improve. | 请提交遇到的问题或 Bug。
title: "[Bug]"
labels:
  - bug
assignees: rockbenben
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Make sure that you follow these statements.
      options:
        - label: I have searched [issues](https://github.com/rockbenben/ChatGPT-Shortcut/issues?q=)
          required: true

  - type: markdown
    attributes:
      value: |
        ## Describe the bug | 问题描述

        > If applicable, add screenshots and log to help explain your problem.
        > 如果方便的话，请添加屏幕截图以帮助解决你的问题。

  - type: textarea
    id: description
    attributes:
      label: Describe the bug | 问题描述
      description: A clear and concise description of what the bug is. | 请描述一下你遇到的问题。
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context | 补充说明
      description: If you are not reporting something obvious, a minimal reproduction repo and related log is required.
      placeholder: Add any other context about the problem here. Especially the issue occurs in certain OS, browser or configuration.
