name: Feature request | 功能需求
description: Suggest an idea for this project
title: "[Feature]"
labels:
  - enhancement
assignees: rockbenben
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Make sure that you follow these statements.
      options:
        - label: I searched existing issues and no one else requests similar feature. | 我搜索了现有的问题，没有人要求类似的功能。
          required: true

        - label: I think that 25%+ users are positive towards this feature. | 我认为 25% 以上的用户需要这个功能。
          required: true

  - type: textarea
    id: feature
    attributes:
      label: Describe the feature | 功能/建议
      description: What's it for and why you want? | 你想要新增或者改进什么功能？
      placeholder: A clear and concise description of what the feature is, and what it will enhance or solve. | 简明扼要地描述该功能是什么，以及它将增强或解决什么问题。
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context | 补充说明
      placeholder: Add any other context or screenshots about the feature request here. | 这个功能有什么可以参考的资料或截图吗？是否可以列举一些。
